GO ?= go
.PHONY: build check race smoke clean
build:
	$(GO) build -o bin/muse ./cmd/muse
check:
	$(GO) fmt ./...
	$(GO) vet ./...
	$(GO) test ./...
	$(GO) build ./...
race:
	$(GO) test -race ./...
smoke: build
	python3 scripts/pty-smoke.py ./bin/muse
clean:
	rm -rf bin
